### ISSUE TITLE
className props does not work

### ISSUE THREAD

**Issue by tomoeine** [inouetakuya/vue-nl2br#19]
Hello,

Thank you for adding "className" props, but it does not work.
It does'nt seem to add to the distribution version though added to src.

dist/vue-nl2br.js
```javascript
exports.default = {
  functional: true,
  props: {
    tag: {
      type: String,
      required: true
    },
    text: {
      type: String,
      required: true
    }
  },
```

**Comment by inouetakuya** [comment]
Sorry for the late response. I released v0.1.2 including "className"

https://github.com/inouetakuya/vue-nl2br/blob/v0.1.2/dist/vue-nl2br.js
