### ISSUE TITLE
does it support dynamic context (like data field from json)

### ISSUE THREAD

**Issue by VirtumartOz** [inouetakuya/vue-nl2br#22]
instead of <nl2br tag="td" :text="`line1\nline2`" class-name="foo bar" />

does it support <nl2br tag="td" :text=item.item_name class-name="foo bar" />

where item.item_name = "line1\nline2"

**Comment by VirtumartOz** [comment]
instead of &lt;nl2br tag="td" :text="`line1\nline2`" class-name="foo bar" /&gt;

does it support

&lt;nl2br tag="td" :text=item.item_name class-name="foo bar" /&gt;

where item.item_name = "line1\nline2"

**Comment by Chouchen** [comment]
It does work with `<nl2br tag="td" :text="item.item_name" class-name="foo bar" />`

**Comment by inouetakuya** [comment]
Sorry for the late response.

Please use the following syntax:

```html
<nl2br tag="td" :text="item.item_name" class-name="foo bar" />
```
