### ISSUE TITLE
Allow null values

### ISSUE THREAD

**Issue by na2axl** [inouetakuya/vue-nl2br#24]
Hello @inouetakuya ,

I'm using your package, but it doesn't work when the passed value in **text** is `null`. I think a better idea is to render nothing, instead of throw an exception.

**Comment by dpslwk** [comment]
Possible needs an option to either render an empty tag or nothing at all

**Comment by inouetakuya** [comment]
> I think a better idea is to render nothing, instead of throw an exception.

I agree.

I would prefer to treat `text: null` the same way as `text: ''`.

In other words, it will render `<p></p>` if properties are `{ tag: 'p', text: null }`.

- ref: https://github.com/inouetakuya/vue-nl2br/blob/3281036607bf3003371bd4fd17c56683515fe818/__tests__/Nl2br.spec.ts#L31-L39

**Comment by inouetakuya** [comment]
https://github.com/inouetakuya/vue-nl2br/issues/24#issuecomment-965913784

> Possible needs an option to either render an empty tag or nothing at all

I don't think the option is needed.

If `myText` is `null`:

- If you want to render an empty tag, write: `<nl2br tag="p" :text="myText" />`
- If you want to render nothing, write: `<nl2br v-if="myText" tag="p" :text="myText" />`
