### ISSUE TITLE
vue should be in peerDependencies

### ISSUE THREAD

**Issue by IlyaSemenov** [inouetakuya/vue-nl2br#4]
Please move `vue@^2` to `peerDependencies` (as most other vue libraries do, e.g. `vue-moment`).

Otherwise `vue-nl2br` pulls extra `vue` package in Nuxt.js projects (where `vue` is not **directly** required).

**Comment by inouetakuya** [comment]
You're right. I will fix.

(So sorry about very long time from this issue created. :bow:)
