### ISSUE TITLE
Why not just use CSS `white-space: pre;`?

### ISSUE THREAD

**Issue by lcherone** [inouetakuya/vue-nl2br#7]
Why not just use CSS `white-space: pre;`?

    .nl2br {
        white-space: pre;
    }

    <p class="nl2br">{{ text }}</p>

**Comment by clytras** [comment]
In my case, ` white-space: pre` and bootstrap ` whitespace-pre` class is breaking an auto column on smal screens, so I had to remote it and use `vue-nl2br`,

**Comment by inouetakuya** [comment]
Yes, `white-space: pre;` is enough in most casses, but `vue-nl2br` is needed in minor cases like above example. 

(So sorry about very long time from this issue created. :bow:)

**Comment by inouetakuya** [comment]
There is a case in which `white-space: pre-wrap;`is enough even if it sticks over with`white-space: pre;` 

white-space | MDN
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

### white-space: pre; 

![image](https://user-images.githubusercontent.com/634357/50627567-61eda580-0f77-11e9-9cd9-2374b52db00a.png)

### white-space: pre-wrap;

![image](https://user-images.githubusercontent.com/634357/50627575-687c1d00-0f77-11e9-94f2-4810a1b5721d.png)
